FROM node:18 AS build

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN yarn

COPY . .

RUN yarn run build
RUN yarn cache clean

FROM node:18-alpine3.21

COPY --from=build /usr/src/app/package.json ./package.json
COPY --from=build /usr/src/app/dist ./dist 
COPY --from=build /usr/src/app/node_modules ./node_modules 

EXPOSE 5173

CMD ["yarn", "run", "start"]